import Link from "next/link";
import { readyWorkspaceUser } from "@/lib/page-access";
import { rows } from "@/lib/db";
import { CHAINS, type Chain } from "@/lib/chains";
import { Address, ChainBadge, EmptyState, PageHeader, Time, formatAmount } from "@/components/ui";
type Event={id:string;wallet_id:string;wallet_name:string;address:string;chain:Chain;tx_hash:string;event_type:string;direction:string;amount:string|null;token_symbol:string|null;usd_value:string|null;occurred_at:Date};
export default async function ActivityPage({searchParams}:{searchParams:Promise<{q?:string;chain?:string;type?:string;page?:string}>}){
  const user=await readyWorkspaceUser();if(!user)return null;const p=await searchParams;const q=p.q?.slice(0,100)??"";const chain=p.chain&&p.chain in CHAINS?p.chain:null;const type=["TRANSFER","NFT_TRANSFER"].includes(p.type??"")?p.type:null;
  const page=Math.max(1,Math.min(10000,Number(p.page)||1));
  const events=await rows<Event>(`SELECT e.id,e.wallet_id,w.name AS wallet_name,w.address,e.chain,e.tx_hash,e.event_type,e.direction,e.amount,e.token_symbol,e.usd_value,e.occurred_at
    FROM wallet_events e JOIN wallets w ON w.id=e.wallet_id WHERE e.user_id=$1
    AND ($2::text IS NULL OR e.chain=$2) AND ($3::text IS NULL OR e.event_type=$3)
    AND ($4='' OR w.name ILIKE '%'||$4||'%' OR w.address ILIKE '%'||$4||'%' OR e.tx_hash ILIKE '%'||$4||'%'
      OR e.token_symbol ILIKE '%'||$4||'%' OR e.token_address ILIKE '%'||$4||'%')
    ORDER BY e.occurred_at DESC,e.id DESC LIMIT 50 OFFSET $5`,[user.id,chain,type,q,(page-1)*50]);
  function pageUrl(n:number){return `/activity?${new URLSearchParams({q,chain:chain??"",type:type??"",page:String(n)})}`;}
  return <><PageHeader eyebrow="OBSERVE / ACTIVITY" title="Activity feed" description="A searchable record of provider verified transfers. New events appear after the worker syncs."/><section className="panel"><form className="filter-bar"><input name="q" defaultValue={q} placeholder="Wallet, address, transaction hash" aria-label="Search activity"/><select name="chain" defaultValue={chain??""} aria-label="Filter by chain"><option value="">All chains</option>{Object.entries(CHAINS).map(([id,c])=><option key={id} value={id}>{c.label}</option>)}</select><select name="type" defaultValue={type??""} aria-label="Filter by event type"><option value="">All events</option><option value="TRANSFER">Transfer</option><option value="NFT_TRANSFER">NFT transfer</option></select><button className="button secondary">Apply</button></form>{events.length?<div className="feed-list">{events.map(e=><article className="feed-row" key={e.id}><span className={`event-mark ${e.direction}`}/><div className="feed-wallet"><Link prefetch={false} href={`/wallets/${e.wallet_id}`}><strong>{e.wallet_name}</strong></Link><span><Address value={e.address}/></span></div><div className="feed-action"><span className={`direction ${e.direction}`}>{e.direction.toUpperCase()}</span><strong>{e.event_type.replace("_"," ")}</strong><span>{formatAmount(e.amount,e.token_symbol)}</span></div><div className="feed-chain"><ChainBadge chain={e.chain}/><small>USD {e.usd_value?`$${e.usd_value}`:"unverified"}</small></div><div className="feed-time"><Time value={e.occurred_at}/><a href={`${CHAINS[e.chain].explorer}${e.tx_hash}`} target="_blank" rel="noopener noreferrer" className="text-link">Transaction ↗</a></div></article>)}</div>:<EmptyState title="No matching activity" body="Try a broader filter, or add and sync a wallet first." href="/wallets" label="Open watchlist"/>}<div className="pagination">{page>1&&<Link prefetch={false} className="button secondary" href={pageUrl(page-1)}>← Previous</Link>}{events.length===50&&<Link prefetch={false} className="button secondary" href={pageUrl(page+1)}>Next →</Link>}</div></section></>;
}
