import Link from "next/link";
import { ArrowUpRight, Bell, Database, Plus, Wallet } from "lucide-react";
import { currentUser } from "@/lib/auth";
import { one, rows } from "@/lib/db";
import { Address, ChainBadge, EmptyState, PageHeader, StatusBadge, Time, formatAmount } from "@/components/ui";
import type { Chain } from "@/lib/chains";
type Stats={wallets:string;events_24h:string;alerts_sent:string;active_chains:string};
type WalletRow={id:string;name:string;address:string;chain:Chain;sync_status:string;created_at:Date};
type EventRow={id:string;wallet_id:string;wallet_name:string;event_type:string;direction:string;amount:string|null;token_symbol:string|null;chain:Chain;occurred_at:Date};
export default async function OverviewPage(){
  const user=(await currentUser())!;
  const [stats,wallets,events]=await Promise.all([
    one<Stats>(`SELECT (SELECT count(*) FROM wallets WHERE user_id=$1)::text AS wallets,
      (SELECT count(*) FROM wallet_events WHERE user_id=$1 AND occurred_at>now()-interval '24 hours')::text AS events_24h,
      (SELECT count(*) FROM discord_deliveries d JOIN alert_events ae ON ae.id=d.alert_event_id JOIN alert_rules ar ON ar.id=ae.rule_id WHERE ar.user_id=$1 AND d.status='sent')::text AS alerts_sent,
      (SELECT count(DISTINCT chain) FROM wallets WHERE user_id=$1)::text AS active_chains`,[user.id]),
    rows<WalletRow>("SELECT id,name,address,chain,sync_status,created_at FROM wallets WHERE user_id=$1 ORDER BY created_at DESC LIMIT 5",[user.id]),
    rows<EventRow>("SELECT e.id,e.wallet_id,w.name AS wallet_name,e.event_type,e.direction,e.amount,e.token_symbol,e.chain,e.occurred_at FROM wallet_events e JOIN wallets w ON w.id=e.wallet_id WHERE e.user_id=$1 ORDER BY e.occurred_at DESC LIMIT 8",[user.id])
  ]);
  return <><PageHeader eyebrow="WORKSPACE / OVERVIEW" title="Intelligence overview" description="Verified activity from wallets you track. Unavailable data stays clearly marked." action={<Link className="button primary" href="/wallets?add=1"><Plus size={16}/> Add wallet</Link>}/><div className="stats-grid"><div className="stat-card"><span><Wallet size={17}/> TRACKED WALLETS</span><strong>{stats?.wallets??"0"}</strong><small>Private watchlist</small></div><div className="stat-card"><span><ArrowUpRight size={17}/> EVENTS / 24H</span><strong>{stats?.events_24h??"0"}</strong><small>Verified on-chain transfers</small></div><div className="stat-card"><span><Bell size={17}/> ALERTS SENT</span><strong>{stats?.alerts_sent??"0"}</strong><small>Discord deliveries</small></div><div className="stat-card"><span><Database size={17}/> ACTIVE CHAINS</span><strong>{stats?.active_chains??"0"}</strong><small>Networks in watchlist</small></div></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><span className="eyebrow">MONITORING</span><h2>Watchlist</h2></div><Link href="/wallets" className="text-link">View all →</Link></div>{wallets.length?<div className="compact-list">{wallets.map(w=><Link href={`/wallets/${w.id}`} className="compact-row" key={w.id}><div className="wallet-avatar">{w.name.slice(0,2).toUpperCase()}</div><div className="row-primary"><strong>{w.name}</strong><span><Address value={w.address}/> · <ChainBadge chain={w.chain}/></span></div><StatusBadge status={w.sync_status}/></Link>)}</div>:<EmptyState title="No wallets tracked" body="Add a wallet address to begin building your intelligence feed." href="/wallets?add=1" label="Add first wallet"/>}</section><section className="panel"><div className="panel-heading"><div><span className="eyebrow">OBSERVATION</span><h2>Recent activity</h2></div><Link href="/activity" className="text-link">Full feed →</Link></div>{events.length?<div className="compact-list">{events.map(e=><Link href={`/wallets/${e.wallet_id}`} className="activity-row" key={e.id}><span className={`event-mark ${e.direction}`}/><div className="row-primary"><strong>{e.wallet_name} <span className="muted normal">{e.direction === "in"?"received":e.direction === "out"?"sent":"transferred"}</span></strong><span>{formatAmount(e.amount,e.token_symbol)} · <ChainBadge chain={e.chain}/></span></div><Time value={e.occurred_at}/></Link>)}</div>:<EmptyState title="No verified activity yet" body="The worker will populate this feed when a configured provider returns transactions."/>}</section></div><p className="data-note">Data note · Dollar values, ownership, swaps, and relationships are not inferred from simple transfers. Unknown values stay unknown.</p></>;
}
