"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
type Wallet={id:string;name:string;address:string;chain:string};
export function EntityMembership({entityId,available,members}:{entityId:string;available:Wallet[];members:Wallet[]}){
  const router=useRouter();const [walletId,setWalletId]=useState(available[0]?.id??"");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(!available.some(w=>w.id===walletId))setWalletId(available[0]?.id??"");},[available,walletId]);
  async function add(){if(!walletId)return;setBusy(true);setError("");try{const response=await fetch(`/api/entities/${entityId}/wallets`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({walletId})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not add wallet");router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Request failed");}finally{setBusy(false);}}
  async function remove(id:string){setBusy(true);setError("");try{const response=await fetch(`/api/entities/${entityId}/wallets/${id}`,{method:"DELETE"});if(!response.ok)throw new Error("Could not remove wallet");router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Request failed");}finally{setBusy(false);}}
  return <><div className="member-list">{members.map(w=><div className="member-row" key={w.id}><div><strong>{w.name}</strong><span className="mono">{w.chain} · {w.address.slice(0,8)}…{w.address.slice(-5)}</span></div><button className="text-button destructive" disabled={busy} onClick={()=>remove(w.id)}>Remove</button></div>)}</div>{available.length?<div className="member-add"><select aria-label="Wallet to add" value={walletId} onChange={e=>setWalletId(e.target.value)}>{available.map(w=><option value={w.id} key={w.id}>{w.name} · {w.chain}</option>)}</select><button className="button secondary" disabled={busy||!walletId} onClick={add}>{busy?"Working…":"Add wallet"}</button></div>:<p className="field-help member-empty">All tracked wallets are assigned or none are available. Add another wallet from the watchlist.</p>}{error&&<p className="form-error member-error" role="alert">{error}</p>}</>;
}
export function EntityEdit({entity}:{entity:{id:string;name:string;category:string|null;notes:string|null}}){const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);
    try{const response=await fetch(`/api/entities/${entity.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:form.get("name"),category:form.get("category"),notes:form.get("notes")})});const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not save entity");setOpen(false);router.refresh();}catch(reason){setError(reason instanceof Error?reason.message:"Request failed");}finally{setBusy(false);}}
  async function remove(){if(!confirm("Delete this entity grouping? Wallets and their events will remain in your watchlist."))return;setBusy(true);const response=await fetch(`/api/entities/${entity.id}`,{method:"DELETE"});if(response.ok){router.push("/entities");router.refresh();}else{setError("Could not delete entity");setBusy(false);}}
  return <><div className="action-group"><button className="button secondary" onClick={()=>setOpen(!open)}>{open?"Close editor":"Edit entity"}</button><button className="button danger" onClick={remove} disabled={busy}>Delete</button></div>{error&&<p className="form-error">{error}</p>}{open&&<form className="form-stack edit-form" onSubmit={save}><label>Name<input name="name" required defaultValue={entity.name}/></label><label>Category<input name="category" defaultValue={entity.category??""}/></label><label>Notes<textarea name="notes" rows={3} defaultValue={entity.notes??""}/></label><button className="button primary" disabled={busy}>{busy?"Saving…":"Save changes"}</button></form>}</>;
}
