"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { Activity, Bell, Database, LayoutDashboard, Menu, Network, Radio, Search, Settings, Users, Wallet, X } from "lucide-react";
const links=[{href:"/overview",label:"Overview",icon:LayoutDashboard},{href:"/search",label:"Search",icon:Search},{href:"/wallets",label:"Wallets",icon:Wallet},{href:"/entities",label:"Entities",icon:Users},{href:"/activity",label:"Activity",icon:Activity},{href:"/network-graph",label:"Network graph",icon:Network},{href:"/alerts",label:"Alerts",icon:Bell},{href:"/discord",label:"Discord",icon:Radio},{href:"/data-sources",label:"Data sources",icon:Database}];
export function Nav({username}:{username:string}) {
  const pathname=usePathname(); const router=useRouter(); const [open,setOpen]=useState(false);
  async function logout(){ await fetch("/api/auth/logout",{method:"POST"}); router.push("/login"); router.refresh(); }
  return <><header className="mobile-header"><Link href="/overview" className="brand-mark">WG<span>↗</span></Link><button className="icon-button" aria-label={open?"Close navigation":"Open navigation"} onClick={()=>setOpen(!open)}>{open?<X size={21}/>:<Menu size={21}/>}</button></header>{open&&<button className="nav-backdrop" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={`sidebar ${open?"open":""}`}><Link href="/overview" className="sidebar-brand" onClick={()=>setOpen(false)}><span className="brand-mark">WG<span>↗</span></span><span>WALLETGRAPH<small>INTELLIGENCE TERMINAL</small></span></Link><div className="nav-caption">WORKSPACE</div><nav aria-label="Primary navigation">{links.map(({href,label,icon:Icon})=><Link href={href} key={href} className={`nav-link ${pathname===href||pathname.startsWith(href+"/")?"active":""}`} onClick={()=>setOpen(false)}><Icon size={17}/><span>{label}</span></Link>)}</nav><div className="nav-caption later">EXPANSION</div><div className="nav-future"><span>Clusters</span><span>Token intelligence</span><small>Planned for Phase 2</small></div><div className="sidebar-bottom"><div className="connection-indicator"><span className="signal-dot"/> LIVE WORKSPACE</div><span className="account-email" title={username}>{username}</span><button className="nav-link logout" onClick={logout}><Settings size={17}/> Sign out</button></div></aside></>;
}
