"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CHAINS, type Chain } from "@/lib/chains";
export function WalletForm({initialChain="ethereum",initialAddress=""}:{initialChain?:Chain;initialAddress?:string}){
  const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [name,setName]=useState(""); const [address,setAddress]=useState(initialAddress); const [chain,setChain]=useState<Chain>(initialChain);
  const [tags,setTags]=useState(""); const [category,setCategory]=useState(""); const [entityName,setEntityName]=useState(""); const [notes,setNotes]=useState(""); const [priority,setPriority]=useState("normal"); const [alertLevel,setAlertLevel]=useState("all"); const [backfill,setBackfill]=useState("latest");
  async function submit(event:React.FormEvent){
    event.preventDefault();setBusy(true);setError("");
    try { const response=await fetch("/api/wallets",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,address,chain,tags:tags.split(",").map(x=>x.trim()).filter(Boolean),category,entityName,notes,priority,alertLevel,backfill})});
      const data=await response.json();if(!response.ok)throw new Error(data.error??"Could not add wallet");router.push(`/wallets/${data.id}`);router.refresh();
    }catch(error){setError(error instanceof Error?error.message:"Request failed");}finally{setBusy(false);}
  }
  return <form onSubmit={submit} className="form-stack"><div className="form-row"><label>Wallet name<input required value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="e.g. Treasury 01"/></label><label>Chain<select value={chain} onChange={e=>setChain(e.target.value as Chain)}>{Object.entries(CHAINS).map(([id,c])=><option value={id} key={id}>{c.label}</option>)}</select></label></div><label>Wallet address<input required value={address} onChange={e=>setAddress(e.target.value)} placeholder={chain==="solana"?"Solana address":"0x..."} spellCheck={false} className="mono"/></label><div className="form-row"><label>Tags <span className="optional">comma separated</span><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Smart Money, Treasury"/></label><label>Category<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Fund / Trader / Protocol"/></label></div><label>Entity <span className="optional">unverified manual label</span><input value={entityName} onChange={e=>setEntityName(e.target.value)} placeholder="Optional entity name"/></label><label>Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} placeholder="Why are you watching this wallet?"/></label><div className="form-row thirds"><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="normal">Normal</option><option value="high">High</option><option value="low">Low</option></select></label><label>Alerts<select value={alertLevel} onChange={e=>setAlertLevel(e.target.value)}><option value="all">Enabled</option><option value="off">Off</option></select></label><label>History<select value={backfill} onChange={e=>setBackfill(e.target.value)}><option value="latest">From now</option><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option><option value="full">Full history</option></select></label></div><p className="field-help">History sync runs in the worker. Provider limits may affect completion; progress appears on the wallet page.</p>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?"Adding wallet…":"Add to watchlist →"}</button></form>;
}
